build:
  maxIssues: 10
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1

config:
  validation: true

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

style:
  MagicNumber:
    active: false

comments:
  CommentOverPrivateFunction:
    active: false